# Generated by Django 5.1.3 on 2024-11-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyek',
            fields=[
                ('id_proyek', models.AutoField(primary_key=True, serialize=False)),
                ('type_proyek', models.CharField(max_length=50)),
                ('nama_proyek', models.CharField(max_length=100)),
                ('lokasi_proyek', models.CharField(max_length=255)),
            ],
        ),
    ]
