# Generated by Django 5.1.3 on 2024-11-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_proyek'),
    ]

    operations = [
        migrations.CreateModel(
            name='Petani',
            fields=[
                ('id_petani', models.AutoField(primary_key=True, serialize=False)),
                ('presentase_keuntungan', models.DecimalField(decimal_places=2, max_digits=5)),
                ('jatuh_tempo', models.DateField()),
                ('rata_rata_keuntungan', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
